services:
  frontend:
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_OIDC_CLIENT_ID=mocked-responses-client
      - VITE_OIDC_CLIENT_SECRET=test
      - VITE_OIDC_AUTHORITY=http://localhost:8080/realms/mocked-responses
      - VITE_OIDC_POST_LOGOUT_REDIRECT_URI_SUFFIX=portal/
      - VITE_OIDC_SILENT_REDIRECT_URI_SUFFIX=silent-reniew/
      - VITE_OIDC_REDIRECT_URI_SUFFIX=authenticated/
      - VITE_API_URL=http://localhost:3000
      - VITE_API_VERSION=v1
    build:
      target: development
    depends_on:
      - keycloak
      - api

  postgres:
    image: postgres:15.6
    container_name: postgres_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./devops/keycloak/imports:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm --verbose
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  api:
    build:
      context: ./devops/test-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
